### ISSUE TITLE
org.flatpak.Builder not on flathub

### ISSUE THREAD

**Issue by WillowMist** [Siroj42/wasp-companion#4]
It looks like org.flatpak.Builder as been removed from flathub.  Are there any alternatives install methods you could detail?

**Comment by Siroj42** [comment]
Sorry for not replying to you earlier. Flatpak Builder should still be available on flathub (I can still install it from there). However, I've just added another install method: You can get the latest x86_64 build from Github Actions now. Just download & unzip the artifact, then install from the .flatpak file.

**Comment by WillowMist** [comment]
That helped immensely.  I got it going and it synced the time.  Is that the only complete feature at the moment?  I just want to be sure it built properly.

**Comment by Siroj42** [comment]
In addition to the time sync, it also forwards notifications to the watch and allows you to control any MPRIS-compatible audio/video player with wasp-os' music player app.
